name: Tests
on:
  push:
    branches:
      - main
  pull_request:

# Declare default permissions as read only.
permissions: read-all

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      # Set up Flutter.
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
          architecture: x64 # optional, x64 or arm64
      - run: flutter doctor -v

      # Checkout gallery code and get packages.
      - uses: actions/checkout@v3
      - run: flutter pub get

      # Analyze, check formatting, and run unit tests.
      - run: flutter analyze
      - name: Ensure the Dart code is formatted correctly
        run: dart format --set-exit-if-changed .
      - name: Run Flutter unit tests
        run: flutter test

#   benchmark-test:
#     name: Benchmark tests
#     runs-on: ubuntu-latest
#     steps:
#       # Set up Flutter.
#       - uses: subosito/flutter-action@v2
#         with:
#           channel: 'stable' # or: 'beta', 'dev' or 'master'
#           cache: true
#           cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
#           cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
#           architecture: x64 # optional, x64 or arm64
#       - run: flutter doctor -v

#       # Checkout gallery code and get packages.
#       - uses: actions/checkout@v3
#       - run: flutter pub get

#       - run: flutter test test_benchmarks

#   golden-test:
#     name: Golden tests
#     runs-on: macos-latest
#     steps:
#       # Set up Flutter.
#       - uses: subosito/flutter-action@v2
#         with:
#           channel: 'stable' # or: 'beta', 'dev' or 'master'
#           cache: true
#           cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
#           cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
#           architecture: x64 # optional, x64 or arm64
#       - run: flutter doctor -v

#       # Checkout gallery code and get packages.
#       - uses: actions/checkout@v3
#       - run: flutter pub get

#       # Run the golden tests and upload failed test artifacts.
#       - run: flutter test test_goldens
#       - name: Upload goldens if tests fail
#         uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
#         if: failure()
#         with:
#           name: goldens
#           path: test_goldens/failures/